### ISSUE TITLE
Put HTML content before editor

### ISSUE THREAD

**Issue by amiceli** [powmedia/backbone-forms#456]
I've opened this issue : #455 . It was closed but the problem was not resolved.

Thanks for your help

**Comment by powmedia** [comment]
Can you create a jsfiddle showing the issue?

**Comment by amiceli** [comment]
The [JSFiddle](https://jsfiddle.net/usg5qe0b/1/)

I use a custom template for my checkbox fields : 

    var checkboxFieldTemplate = _.template('\
        <div class="form-group field-<%= key %>">\
            <span data-editor>\
                <label class="checkboxLabel" for="<%= editorId %>"><%= title %></label>\
             </span>\
             <p class="help-block"><%= help %></p>\
        </div>\
    ');

But the input is alway added after the label. There is a way (without jQuery DOM manipulation) to put the input before the label ?

**Comment by gebrits** [comment]
isn't this a pure css issue?
See: https://jsfiddle.net/cLp04jsj/1/

**Comment by powmedia** [comment]
Isn't this what you need? I just switched round the order of the HTML elements in the template:

https://jsfiddle.net/usg5qe0b/3/

**Comment by amiceli** [comment]
No, the label and the input must be in the same parent element, like this : 

    <span data-editor="">
          <input id="c1_death" name="death" type="checkbox">
          <label class="checkboxLabel" for="c1_death">Death</label> 
     </span>

The place of the element is important for some CSS rules like : 

    input:checked+label {
        
    }

Thanks for your help

**Comment by powmedia** [comment]
I think for that you'll either need to use DOM manipulation, or you could
create a custom editor. See
https://github.com/powmedia/backbone-forms#custom-editors

**Comment by amiceli** [comment]
Ok thanks.
There is a way to create an input manually ? For example : 

    var checkboxFieldTemplate = _.template('\
        <span>
            <input type="checkbox" name="<%= nameHere %>" /> 
        </span>
    ');

**Comment by nycitt** [comment]
@powmedia I'm having a similar issue. I am trying to create a textarea with a character counter (which lives in a `span` outside of the textarea). I would like to create a custom editor type (`TextareaWithCounter`). 

The problem is, in `render`, when I try to attach the `span` after the editor (using jQuery's `.insertAfter`) it doesn't work (because the element gets rendered BEFORE it's attached to the field's `$el`)

Ideally I would be able to:
1) Create a custom TextareaWithCounter Field View to go along with the TextareaWithCounter Editor View
2) Somehow hook into the form after it's done attaching the editor

**Comment by Blasz** [comment]
Would be great if field/editor templates could be configurable on both a global and field type level without having to create a custom editor.
