### ISSUE TITLE
Focus/Blur events don't work on root element with Backbone.View events hash

### ISSUE THREAD

**Issue by Blasz** [powmedia/backbone-forms#459]
When defining an events hash for a class extending Backbone.Form, the `focus` and `blur` events don't work on the root element.

I.e. 

```
return myView = (function(_super) {
      __extends(myView, _super);

      function myView() {
        ...
        return myView.__super__.constructor.apply(this, arguments);
      }

      myView.prototype.events = {
        'change': 'onChange',
        'focus': 'onFocus',
        'blur': 'onBlur',
        'submit': 'onSubmit'
      };

      return myView;
    })(Backbone.Form);
```

An input selector has to be used for the events to to be fired from the declared events hash:
```
      myView.prototype.events = {
        'change': 'onChange',
        'focus input': 'onFocus',
        'blur input': 'onBlur',
        'submit': 'onSubmit'
      };
```

Or the events must be manually bound using `on` after the render function
```
myView.prototype.render = function() {
        console.log('rendering');
        myView.__super__.render.apply(this, arguments);
        return this.on('blur', function() {
          return console.log('blur');
        });
      };
```

Note that the the change and submit events work as expected.

**Comment by glenpike** [comment]
I would suggest that this may not be a bug - the Form is merely relaying 'focus' and 'blur' events from the editor as "general" events to listen to - they don't relay the event argument.

Because you are extending the Form, you would probably want to handle specific events "internally", so targeting the inputs with the event hash makes sense, or overriding the handleEditorEvent method may be more beneficial.

For code which consumes your extended form, you should still get the focus / blur events, providing you don't break the super-class methods.

For now, I will close this, but if you have a use-case where this is completely valid, please reopen it with details and we can discuss further.
