### ISSUE TITLE
reasons bb-forms is still fixed to bb ~1.2? 

### ISSUE THREAD

**Issue by gebrits** [powmedia/backbone-forms#539]
Any known reasons why backbone-forms is still fixed to backbone minor version 1.2? (i.e.: package.json entry `backbone: ~1.1.2`. I.e.: any reason NOT to use the more relaxed `backbone: ^1.1.2` ? Afaik, but not sure which is why I'm asking, there haven't been any breaking changes in backbone since.

background: after inspecting the size of my JS-bundle it turns out I'm using 2 separate releases of backbone. 1) the latest I'm referencing myself (package.json: `backbone: ^1.3.3`) and 2) the one backbone.forms depends on. This gives me itches all over. 

Anu solutions?

**Comment by glenpike** [comment]
No specific reason, bar not changing it yet.  We're working towards a release so will update the version too.

**Comment by gebrits** [comment]
ok cool.

**Comment by DavidUnzue** [comment]
I'm using the latest release of Backbone (v1.3.3) all over my application and because of backbone-forms loading Backbone v1.1.2 I get some conflict issues. I'm requiring backbone-forms with Browserify and not able to bind jQuery like shown in the docs, so if I do:
```
var Backbone = require('backbone');
Backbone.$ = require('jquery')
var Forms = require('backbone-forms');
```
I get the error:
```
Backbone.$ is not a function
```

If I manually change the version of Backbone internally loaded by backbone-forms to the newest one (v1.3.3), the issue disappears.

@glenpike When are you planning to update to the new version? Or what would be the solution here?

**Comment by glenpike** [comment]
This sounds more like a tooling issue - Backbone Forms will just require the version of Backbone that is available, but there could be an issue with duplicate versions in the tree.

Something like this problem? https://stackoverflow.com/questions/27931982/how-do-i-prevent-browserify-from-including-multiple-versions-of-sub-dependencies

Regarding updates.  I've not had chance to work on this project for a while, so updating hasn't been on my radar - sorry.  @benflodge were you looking at upgrading the version of Backbone, or have you done this successfully?
